/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scenarios */
        get: operations["scenarios_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Topology */
        get: operations["topology_topology_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HealthResponse */
        HealthResponse: {
            /** Kafka */
            kafka: boolean;
            /** Neo4J */
            neo4j: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        /** Layout */
        Layout: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * ScenarioInfo
         * @description Never includes ground truth.
         */
        ScenarioInfo: {
            /** Description */
            description: string;
            /** Fix Flow Available */
            fix_flow_available: boolean;
            /** Id */
            id: string;
            /**
             * Priority
             * @enum {string}
             */
            priority: "P0" | "P1";
            /** Title */
            title: string;
        };
        /** ServiceNode */
        ServiceNode: {
            /** Customer Facing */
            customer_facing: boolean;
            /**
             * Health
             * @default healthy
             * @enum {string}
             */
            health: "healthy" | "degraded" | "failing";
            /**
             * Kind
             * @enum {string}
             */
            kind: "service" | "database" | "cache";
            layout: components["schemas"]["Layout"];
            /** Name */
            name: string;
            /**
             * Tier
             * @enum {string}
             */
            tier: "customer_facing" | "edge" | "internal" | "data";
        };
        /** TopologyEdge */
        TopologyEdge: {
            /** Blocking */
            blocking: boolean;
            /** Source */
            source: string;
            /** Target */
            target: string;
        };
        /** TopologyResponse */
        TopologyResponse: {
            /** Edges */
            edges: components["schemas"]["TopologyEdge"][];
            /** Services */
            services: components["schemas"]["ServiceNode"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    scenarios_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioInfo"][];
                };
            };
        };
    };
    topology_topology_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopologyResponse"];
                };
            };
        };
    };
}
